name: Pull files from Syncxv/vc-timezones
env:
  SOURCE_REPO: Syncxv/vc-timezones
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com
  THE_SERVER: ${{ github.server_url }}
  PATH_SOURCE_CHECKOUT: temp_folder

on:
  workflow_dispatch:
  push:

jobs:
  pull-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SOURCE_REPO }}
          path: ${{ env.PATH_SOURCE_CHECKOUT }}

      - name: Update
        run: |
          rm -rf $PATH_SOURCE_CHECKOUT/.git
          rsync -a --delete $PATH_SOURCE_CHECKOUT/ patches/src/userplugins/vc-timezones
          rm -rf $PATH_SOURCE_CHECKOUT
          
      - name: Commit
        run: |
          git pull
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git add patches/src/userplugins/vc-timezones
          git commit -m "Pulled files from $THE_SERVER/$SOURCE_REPO." patches/src/userplugins/vc-timezones

      - name: Push
        run: |
          git push