name: Pull files from philhk/vencord
env:
  SOURCE_REPO: philhk/vencord
  USERNAME: ${{ github.actor }}
  ADDRESS_SUFFIX: users.noreply.github.com
  THE_SERVER: ${{ github.server_url }}
  PATH_SOURCE_CHECKOUT: temp_folder

on:
  workflow_dispatch:
  push:

jobs:
  pull-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SOURCE_REPO }}
          path: ${{ env.PATH_SOURCE_CHECKOUT }}

      - name: Update
        run: |
          cd $PATH_SOURCE_CHECKOUT
          rsync -a --delete src/plugins/betterScreenshare.desktop ../patches/src/userplugins/
          rsync -a --delete src/plugins/betterMicrophone.desktop ../patches/src/userplugins/
          rsync -a --delete src/plugins/philsPluginLibrary ../patches/src/userplugins/
          cd ..
          rm -rf $PATH_SOURCE_CHECKOUT
          
      - name: Commit
        run: |
          git pull
          git config user.name "$USERNAME"
          git config user.email "$USERNAME@$ADDRESS_SUFFIX"
          git add patches/src/userplugins/betterScreenshare.desktop
          git add patches/src/userplugins/betterMicrophone.desktop
          git add patches/src/userplugins/philsPluginLibrary
          git commit -m "Pulled files from $THE_SERVER/$SOURCE_REPO."

      - name: Push
        run: |
          git push